@extends('layouts.app')
@section('title', 'Centro de operaciones · Dev Orchestrator')
@push('head')<meta http-equiv="refresh" content="20">@endpush
@section('content')
<div class="page-heading"><div><p class="eyebrow">MONITOR / EN VIVO</p><h1>Centro de operaciones</h1><p class="muted">Estado de requerimientos, agentes y workers. Se actualiza cada 20 segundos.</p></div><a class="button primary" href="{{ route('requirements.create') }}">+ Nuevo requerimiento</a></div>
<div class="metrics">
@foreach(['RECEIVED'=>'Nuevos','ANALYZING'=>'Analizando','PLANNING'=>'Planificando','QUEUED'=>'En cola','IMPLEMENTING'=>'Ejecutándose','TESTING'=>'Probando','WAITING_APPROVAL'=>'Aprobación','COMPLETED'=>'Completados','FAILED'=>'Fallidos'] as $key=>$label)
<div class="metric"><span>{{ $label }}</span><strong>{{ $counts[$key] ?? 0 }}</strong><small>{{ $key }}</small></div>
@endforeach
</div>
<div class="grid two">
<section class="panel"><div class="panel-head"><div><p class="eyebrow">INFRAESTRUCTURA</p><h2>Workers</h2></div><a href="{{ route('workers.index') }}">Ver todos →</a></div><div class="table-wrap"><table><thead><tr><th>Worker</th><th>Estado</th><th>Trabajo actual</th><th>Heartbeat</th></tr></thead><tbody>@forelse($workers as $worker)<tr><td><b>{{ $worker->name }}</b><small class="block">{{ $worker->uuid }}</small></td><td><span class="badge {{ strtolower($worker->status) }}">{{ $worker->status }}</span></td><td>@foreach($worker->executions as $execution){{ $execution->task?->project?->slug }} · #{{ $execution->task_id }}@endforeach</td><td>{{ $worker->last_heartbeat_at?->diffForHumans() ?? 'Nunca' }}</td></tr>@empty<tr><td colspan="4" class="empty">Sin workers configurados.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><p class="eyebrow">AGENTES</p><h2>En ejecución</h2></div></div><div class="table-wrap"><table><thead><tr><th>Agente</th><th>Tarea / Proyecto</th><th>Duración</th></tr></thead><tbody>@forelse($executions as $execution)<tr><td>{{ $execution->agent }}</td><td><a href="{{ route('executions.show', $execution) }}">{{ $execution->task?->title }}</a><small class="block">{{ $execution->task?->project?->slug }}</small></td><td>{{ $execution->started_at?->diffForHumans(null, true) }}</td></tr>@empty<tr><td colspan="3" class="empty">No hay agentes activos.</td></tr>@endforelse</tbody></table></div></section>
</div>
<div class="grid two lower"><section class="panel"><div class="panel-head"><div><p class="eyebrow">SEGUIMIENTO</p><h2>Requerimientos recientes</h2></div><a href="{{ route('requirements.index') }}">Ver todos →</a></div><div class="table-wrap"><table><thead><tr><th>Requerimiento</th><th>Proyecto</th><th>Estado</th></tr></thead><tbody>@forelse($recent as $item)<tr><td><a href="{{ route('requirements.show', $item) }}">#{{ $item->id }} {{ $item->subject }}</a></td><td>{{ $item->project?->slug ?? 'Por definir' }}</td><td><span class="badge {{ strtolower($item->status) }}">{{ $item->status }}</span></td></tr>@empty<tr><td colspan="3" class="empty">No hay requerimientos.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><p class="eyebrow">AUDITORÍA</p><h2>Actividad</h2></div></div><div class="timeline">@forelse($events as $event)<div class="timeline-item"><div class="timeline-dot"></div><div><time>{{ $event->created_at->format('d/m H:i') }}</time><p><a href="{{ route('requirements.show', $event->requirement_id) }}">#{{ $event->requirement_id }}</a> · {{ $event->action }} @if($event->to_status)→ {{ $event->to_status }}@endif</p><small>{{ $event->actor }}</small></div></div>@empty<p class="empty">Sin actividad todavía.</p>@endforelse</div></section></div>
@endsection
