@extends('layouts.app')
@section('breadcrumb', 'Requerimientos / #'.$requirement->id)
@section('content')
<div class="page-heading"><div><p class="eyebrow">REQUERIMIENTO #{{ $requirement->id }} · {{ $requirement->kind }}</p><h1>{{ $requirement->subject }}</h1><p class="muted">{{ $requirement->project?->name ?? 'Proyecto por definir' }} · {{ $requirement->source }} · {{ $requirement->created_at->format('d/m/Y H:i') }}</p></div><div class="list-actions"><span class="badge {{ strtolower($requirement->status) }}">{{ $requirement->status }}</span><a class="button" href="{{ route('requirements.edit', $requirement) }}">Editar</a></div></div>
<div class="detail-grid"><div class="detail-stack">
<section class="panel"><div class="panel-head"><h2>Requerimiento original</h2></div><div class="panel-body"><dl class="kv"><dt>Fuente</dt><dd>{{ $requirement->source }} · {{ $requirement->external_reference ?? 'Sin referencia' }}</dd><dt>Remitente</dt><dd>{{ $requirement->sender ?? '—' }}</dd><dt>Prioridad / riesgo</dt><dd>{{ $requirement->priority }} / {{ $requirement->risk }}</dd><dt>Resumen</dt><dd>{{ $requirement->summary ?? '—' }}</dd></dl><div class="prose">{{ $requirement->original_content }}</div>@if($requirement->context)<h3>Contexto</h3><div class="prose">{{ $requirement->context }}</div>@endif</div></section>
@if($requirement->kind === 'PROJECT_RESPONSE')
<section class="panel"><div class="panel-head"><h2>Respuesta del proyecto</h2></div><div class="panel-body">
@if($requirement->responded_at)
<p><b>Respuesta registrada</b> · {{ $requirement->responded_at->format('d/m/Y H:i') }} · usuario #{{ $requirement->responded_by_user_id }}</p><div class="prose">{{ $requirement->response_note }}</div>
@elseif($requirement->status === 'WAITING_RESPONSE')
<p class="muted">Responde el correo por el canal habitual. Después registra aquí una nota de lo enviado. Este sistema no envía correos.</p>
<form method="post" action="{{ route('requirements.response', $requirement) }}">@csrf<label>Qué respondiste<textarea name="response_note" required maxlength="4000">{{ old('response_note') }}</textarea></label><div class="form-actions"><button class="button primary">Registrar respuesta y completar</button></div></form>
@else<p class="muted">Pendiente de revisión y respuesta humana.</p>@endif
</div></section>
@else
<section class="panel"><div class="panel-head"><h2>Análisis técnico</h2></div><div class="panel-body">@if($requirement->technical_analysis)<div class="code">{{ json_encode($requirement->technical_analysis, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</div>@else<p class="muted">Pendiente de diagnóstico del worker local.</p>@endif</div></section>
<section class="panel"><div class="panel-head"><h2>Plan y tareas</h2><a href="{{ route('tasks.create', $requirement) }}">+ Crear tarea</a></div><div class="panel-body">@forelse($requirement->plans as $plan)<p><b>Plan v{{ $plan->version }}</b> · {{ $plan->summary }}</p>@empty<p class="muted">Sin plan.</p>@endforelse</div><div class="table-wrap"><table><thead><tr><th>ID / Tarea</th><th>Tipo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>@forelse($requirement->tasks as $task)<tr><td><b>#{{ $task->id }} {{ $task->title }}</b><small class="block">{{ $task->description }}</small></td><td>{{ $task->type }}</td><td><span class="badge {{ strtolower($task->status) }}">{{ $task->status }}</span></td><td>@if(in_array($task->status,['DRAFT','FAILED']))<form class="inline-form" method="post" action="{{ route('tasks.queue',$task) }}">@csrf<button class="button small">{{ $task->status === 'FAILED' ? 'Reintentar' : 'Encolar' }}</button></form>@endif @foreach($task->executions as $execution)<a href="{{ route('executions.show',$execution) }}">Ejecución #{{ $execution->id }}</a> @endforeach</td></tr>@empty<tr><td colspan="4" class="empty">Sin tareas.</td></tr>@endforelse</tbody></table></div></section>
@endif
<section class="panel"><div class="panel-head"><h2>Timeline</h2></div><div class="timeline">@forelse($requirement->events->sortByDesc('id') as $event)<div class="timeline-item"><div class="timeline-dot"></div><div><time>{{ $event->created_at->format('d/m/Y H:i:s') }}</time><p><b>{{ $event->action }}</b> @if($event->to_status){{ $event->from_status }} → {{ $event->to_status }}@endif</p><small>{{ $event->actor }} @if($event->user_id)· usuario #{{ $event->user_id }}@endif @if($event->worker_id)· worker #{{ $event->worker_id }}@endif</small></div></div>@empty<p class="empty">Sin eventos.</p>@endforelse</div></section>
</div><div class="detail-stack">
<section class="panel"><div class="panel-head"><h2>Flujo</h2></div><div class="panel-body"><form method="post" action="{{ route('requirements.transition',$requirement) }}">@csrf<label>Siguiente estado<select name="status">@foreach($nextStatuses as $status)<option>{{ $status }}</option>@endforeach</select></label><div class="form-actions"><button class="button primary" @disabled(empty($nextStatuses))>Cambiar estado</button></div></form></div></section>
@if($requirement->status === 'PLANNING')<section class="panel"><div class="panel-head"><h2>Nuevo plan</h2></div><form class="panel-body" method="post" action="{{ route('requirements.plans.store',$requirement) }}">@csrf<label>Resumen<textarea name="summary" required></textarea></label><div class="form-actions"><button class="button">Crear plan</button></div></form></section>@endif
@if($requirement->kind !== 'PROJECT_RESPONSE')
<section class="panel"><div class="panel-head"><h2>Aprobaciones</h2></div><div class="panel-body">@foreach($requirement->approvals as $approval)<p><b>{{ $approval->action }}</b> <span class="badge {{ strtolower($approval->status) }}">{{ $approval->status }}</span><small class="block">{{ $approval->reason }}</small></p>@if($approval->status === 'PENDING')<div class="list-actions">@foreach(['APPROVED'=>'Aprobar','REJECTED'=>'Rechazar'] as $decision=>$label)<form method="post" action="{{ route('requirements.approvals.decide',[$requirement,$approval]) }}">@csrf<input type="hidden" name="decision" value="{{ $decision }}"><button class="button small">{{ $label }}</button></form>@endforeach</div>@endif
@endforeach
<form method="post" action="{{ route('requirements.approvals.store',$requirement) }}">@csrf<label>Acción<input name="action" required placeholder="Ej. deploy productivo"></label><label>Motivo<textarea name="reason" required></textarea></label><div class="form-actions"><button class="button">Solicitar aprobación</button></div></form></div></section>
@endif
</div></div>
@endsection
